# Generated by Django 5.0 on 2025-09-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_likes_review_likecount_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likeStatus',
            field=models.BooleanField(default=False),
        ),
    ]
