# Generated by Django 5.0 on 2025-09-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_like_id_alter_review_likestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likeStatus',
        ),
    ]
